import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/section/Navbar";
import Contact from "@/components/section/Contact";
import Footer from "@/components/section/Footer";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} antialiased px-2 max-w-6xl m-auto`}
      >
        <div className="fixed  inset-0 -z-10 h-full w-full items-center px-5 py-24 [background:radial-gradient(125%_125%_at_50%_10%,#000_40%,#4a5caa_100%)] "></div>

        <Navbar />
        <div className="max-w-6xl">
          {children}
        </div>
        {/* <Contact/> */}
        <Footer/>
      </body>
    </html>
  );
}
